chore(build-release): Add additional error checking (#7)
* chore(build-release): Add additional error checking for csproj read.

Allow the release check to happen on any PR for verification.

* fix(build-release): Set a GH_TOKEN instead of GITHUB_TOKEN. This is what gh is expecting.

Remove the gh install, it should be on the machines already.

* fix(build-release): Update Release Check from PS to bash

* fix(build-release): Force bash shell usage

* fix(build-release): Update GH Release Version check for Create Release

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -21,26 +21,36 @@ jobs:
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 8.0.x
-       
+
       - name: Get Version
         id: get_version
         shell: pwsh
         run: |
-          $xml = [Xml] (Get-Content ".\RenameEpisodeFiles\RenameEpisodeFiles.csproj")
-          $version = $xml.Project.PropertyGroup.Version
-          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
+            if (Test-Path ".\RenameEpisodeFiles\RenameEpisodeFiles.csproj") {
+                $xml = [Xml] (Get-Content ".\RenameEpisodeFiles\RenameEpisodeFiles.csproj")
+                $version = $xml.Project.PropertyGroup.Version
+                echo "VERSION=$version" >> $env:GITHUB_OUTPUT
+            } else {
+                Write-Error "Missing .csproj file!"
+                exit 1
+            }
 
-      - name: Check if release exists
-        id: check_release
-        if: github.ref == 'refs/heads/master' # Only check for release on master branch
-        shell: pwsh
-        env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-            VERSION: ${{ steps.get_version.outputs.VERSION }}
+      - name: Check Release with GitHub CLI
+        id: gh-release-check
+        shell: bash
         run: |
-          $release = gh release view "v$env:VERSION" 2>&1
-          $exists = $LASTEXITCODE -eq 0
-          echo "EXISTS=$exists" >> $env:GITHUB_OUTPUT
+          TAG_NAME="v${VERSION}"
+          if gh release view "${TAG_NAME}" &>/dev/null; then
+            echo "Release ${TAG_NAME} exists"
+            echo "release_exists=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "Release ${TAG_NAME} does not exist"
+            echo "release_exists=false" >> "$GITHUB_OUTPUT"
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          VERSION: ${{ steps.get_version.outputs.VERSION }}
 
       - name: Restore dependencies
         run: dotnet restore
@@ -52,7 +62,8 @@ jobs:
         run: dotnet publish RenameEpisodeFiles/RenameEpisodeFiles.csproj -c Release --self-contained -r win-x64 -p:PublishSingleFile=true -o publish
 
       - name: Create Release
-        if: github.ref == 'refs/heads/master' && steps.check_release.outputs.EXISTS != 'True' # Only create release when merging to master and if it doesn't exist
+  
+        if: github.ref == 'refs/heads/master' && steps.gh-release-check.outputs.release_exists == 'false' # Only create release when merging to master and if it doesn't exist
         env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             VERSION: ${{ steps.get_version.outputs.VERSION }}
